name: Azure Static Web Apps CI/CD LIVE

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      manual_ref:
        type: string
        description: The tag or hash that needs to be deployed

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    env:
      VITE_MAPBOX_TOKEN: ${{ vars.VITE_MAPBOX_TOKEN }}
      VITE_REMOTE_MENU_BASE_URL: ${{ vars.VITE_REMOTE_MENU_BASE_URL_LIVE }}
      VITE_REMOTE_HEADER_MENU_ID: ${{ vars.VITE_REMOTE_HEADER_MENU_ID }}
      VITE_REMOTE_FOOTER_MENU_ID: ${{ vars.VITE_REMOTE_FOOTER_MENU_ID }}
      VITE_REMOTE_SOCIAL_LINKS_ID: ${{ vars.VITE_REMOTE_SOCIAL_LINKS_ID }}
      VITE_LOCATION_API_URL: ${{ vars.VITE_LOCATION_API_URL_LIVE }}
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        if: "${{ github.event.inputs.manual_ref != '' }}"
        with:
          submodules: true
          lfs: false
          ref: "${{ github.event.inputs.manual_ref }}"
      - uses: actions/checkout@v3
        if: "${{ github.event.inputs.manual_ref == '' }}"
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BRAVE_WAVE_05C9FF40F }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/" # App source code path
          api_location: "" # Api source code path - optional
          output_location: "dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
